ss_trainee/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  get 'contacts' => 'pages#contacts', as: 'contacts'

  resources :posts
end

ss_trainee/app/models/application_record.rb
# frozen_string_literal: true

# default class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ss_trainee/app/models/post.rb
# frozen_string_literal: true

# Class for the posts of blog
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3 }
end

ss_trainee/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

ss_trainee/app/controllers/pages_controller.rb
# frozen_string_literal: true

# New controoler for static pages
class PagesController < ApplicationController
  def about; end
  def contacts; end
end

ss_trainee/app/controllers/posts_controller.rb
# frozen_string_literal: true

# controller for posts
class PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  # post_params method
  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

ss_trainee/app/controllers/stats_controller.rb
# frozen_string_literal: true

# class for test
class StatsController < ApplicationController
  def bark
    'Woof!'
  end
end

ss_trainee/app/helpers/application_helper.rb
# frozen_string_literal: true

# do smth
module ApplicationHelper
end

ss_trainee/app/helpers/pages_helper.rb
# frozen_string_literal: true

# do smth
module PagesHelper
end

ss_trainee/app/helpers/posts_helper.rb
# frozen_string_literal: true

# do smth
module PostsHelper
end

ss_trainee/app/helpers/stats_helper.rb
# frozen_string_literal: true

# do smth
module StatsHelper
end

ss_trainee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SsTrainy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-bold">SoftServe</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark"><%= link_to "Main page", home_path %></span>
      </nav>
      <span class="p-2 text-dark"><%= link_to "Add post", new_post_path %></span>
      <span class="p-2 text-dark"><%= link_to "Contact us", contacts_path %></span>
      <span class="p-2 text-dark"><%= link_to "About us", about_path %></span>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

ss_trainee/app/views/pages/about.html.erb
<h3><center>About my cool company</center></h3>

ss_trainee/app/views/pages/contacts.html.erb
<html>
  <body>
    <center>
      <h1>Let's connect</h1><br>
      <h3>+311932222222<br>
      vecino@f1blog.com</h3>
    </center>
  </body>
</html>

ss_trainee/app/views/posts/edit.html.erb
<h2>Edit post</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <!-- Validation, Show errors to user -->
  <% if @post.errors.any? %> <!-- If there are any errors in the post -->
    <% @post.errors.full_messages.each do |msg| %> <!-- Show them all -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <!-- Add post form -->
  <p>
    Title<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    Text area<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

ss_trainee/app/views/posts/index.html.erb
<h1><center> The main page</center></h1>
<% @post.each do |post| %>
  <div class="alert alert-light">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Read more", post_path(post), :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

ss_trainee/app/views/posts/new.html.erb
<h2>Add new post</h2>
<%= form_for :post, url: posts_path do |f| %>
  <!-- Validation, Show errors to user -->
  <% if @post.errors.any? %> <!-- If there are any errors in the post -->
    <% @post.errors.full_messages.each do |msg| %> <!-- Show them all -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <!-- Add post form -->
  <p>
    <%= f.label :title %> <br/>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :text_area %> <br/>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit('Save Post', {:class => 'btn btn-success'}) %>
  </p>
<% end %>

ss_trainee/app/views/posts/show.html.erb
<h4><center>Your post</center></h4>
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Delete post", post_path(@post), method: :delete, data: {confirm: "Are you crazy? This post will be destroy!!!"}, :class => 'btn btn-danger' %>